### ISSUE TITLE
need to still send rabbitmq message even if no traffic so poseidon knows what happened

### ISSUE THREAD

**Issue by cglewis** [Lab41/PoseidonML#68]
```
2018-02-20T14:17:28+00:00 172.17.0.1 pcap[788]: INFO:__main__:Not enough sessions in pcap
```

**Comment by cglewis** [comment]
You are correct that it is of no use of Poseidon if it can't make predictions.  Currently the workaround would be tweaking the available settings here: https://github.com/CyberReboot/PoseidonML/blob/master/NodeClassifier/config.json (such as session threshold, etc.)

For those changes to take effect, you'll need to fork the project and change your `./vent_startup.yml` in the Poseidon project to point to your fork instead of the `CyberReboot/PoseidonML` one. And then start Poseidon again.

I'm going to open up a follow up issue that would allow for configuration changes on the fly without having to fork - much like Vent does with Poseidon.

**Comment by jaiken06** [comment]
Follow up to this, I have set the session_threshold to 2.

First I tried to evaluate on a directory of pcaps:
`python eval_OneLayer.py ./Training/ FirstTrain.pkl`

Which gave the following error:
`INFO:__main__:Not enough sessions in pcap`

Then I tried to evaluate on a single pcap:
`python eval_OneLayer.py ./Training/Two-IOT161012.pcap FirstTrain.pkl`

Which gave the following error:
```
Traceback (most recent call last):
 File "eval_OneLayer.py", line 420, in <module>
   abnormality = eval_pcap(pcap_path, label=labels[0])
 File "/app/NodeClassifier/eval_SoSModel.py", line 24, in eval_pcap
   data = create_dataset(pcap, label=label)
 File "/app/NodeClassifier/utils/session_sequence.py", line 55, in create_dataset
   model.load(model_path)
 File "/app/NodeClassifier/utils/RandomForestModel.py", line 296, in load
   with open(load_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/models/OneLayerModel.pkl'
```

The reason I have tried both a directory of pcaps and a single pcap is because it says <pcapdir> in the quick start guide so I thought maybe a directory of pcaps but then when reading the code I gathered from the comment at the top that it reads a single pcap.

I have tried this process with multiple different .pkl files trained with varying kinds of pcaps and have been unable to evaluate successfully, any tips or feedback would be appreciated! :)

**Comment by jaiken06** [comment]
Also executing:

`docker run -v ~/Training/One-IOT161012-node1.pcap:/pcaps/eval.pcap cyberreboot/poseidonml:onelayer`

Returns:

```
Traceback (most recent call last):
 File "eval_OneLayer.py", line 354, in <module>
   with open(load_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/models/OneLayerModel.pkl'
```

**Comment by cglewis** [comment]
Sorry for the delay in the response - we just merged in our overhaul which restructures stuff quite a bit and will hopefully cleanup some these issues.  If you don't mind, do you mind pulling down the latest and checking the `README`s and giving that a whirl to see if it behaves better?

**Comment by jaiken06** [comment]
No worries about the delay!

I have pulled the overhaul and started fresh.  I am getting a new error when I try to execute:
`python train_OneLayer.py ./opts/ OverhaulTrain.pkl`

```
Traceback (most recent call last):
 File "train_OneLayer.py", line 9, in <module>
   from poseidonml.OneLayer import OneLayerModel
ImportError: No module named poseidonml.OneLayer
```

**Comment by scottkelso** [comment]
Hi @cglewis, `overhaul` is looking cleaner.

However both myself and @jaiken06 are both not seeing `train_onelayer` update the existing `models/OneLayerModel.pkl`, or create a new one. We tried deleting the existing pkl but `train_onelayer` did not create a new one when running...

```
export PCAP=~/workspace/traffic/test/
make train_onelayer
```

We also tried hard coding in a `model.seve(/test.pkl)` line in `train_onelayer` but this still did not produce an output file. 

In the `DeviceClassifier` README, it says...
> Additionally, you will need to map a place to save the models.

I am assuming that this refers to the `sys.argv` in the `train_OneLayer.py`?  Is there currently a way to set this?

**Comment by cglewis** [comment]
@scottkelso that's a good catch. The model would have been written inside the Docker container. I've updated the Makefile to automatically map it to the filesystem at `/tmp/models`, and updated the README to reflect that.  Thanks!

**Comment by jaiken06** [comment]
That's it working now, thanks very much!
